### ISSUE TITLE
Incorrect "Invalid requirement lines"

### ISSUE THREAD

**Issue by ghickman** [treyhunner/pep438#7]
A couple of dependencies I've seen this error incorrectly from are:
- `elementtree==1.2.7-20070827-preview`
- `djangorestframework-0.X==0.4.0`

The rest framework one is a from a local PyPI instance I'm running but I'd assumed it would just ignore that when it couldn't find it?

**Comment by treyhunner** [comment]
Thanks for reporting this.

It looks like the problem is the dashes in the name and filename which reqfile-parser (now [requirements-parser](https://github.com/davidfischer/requirements-parser)) isn't able to handle right now.

Also it shouldn't raise an exception to the user in exceptional cases.  The `ValueError` should be caught and an "invalid package name or version" or a similar message should be displayed before moving onto the next package.

**Comment by treyhunner** [comment]
As of version 0.5.0 both of those examples work as expected.  There may be others that do not.

**Comment by ghickman** [comment]
Yep that works brilliantly. Thank you!
